name: classfier_uncertain
channels:
  - pytorch
  - anaconda
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - numpy==2.3.2
  - obspy==1.4.1
  - pandas==2.3.1
  - scipy==1.16.0
  - torch==2.4.1